### PR TITLE
Bit constraint/validation and model fixes

### LINKED ISSUE #1834: DoorLockDevice issue in latest v13 builds
Hi, when upgrading to the latest v13 builds (v0.13.0-alpha.0-20250328-6dde053de) , i am getting an exception when creating a door lock device.  To demonstrate, if i add the following lines to the `BridgedDevicesNode.ts` example (after line 124):

```typscript
const name = `Door Lock`;
const endpoint = new Endpoint(
    DoorLockDevice.with(BridgedDeviceBasicInformationServer),
    {
        id: `lock`,
        bridgedDeviceBasicInformation: {
            nodeLabel: name, // Main end user name for the device
            productName: name,
            productLabel: name,
            serialNumber: `node-matter-${uniqueId}-lock`,
            reachable: true,
        },
        doorLock: {
            lockState: 0,
            lockType: 2,
            actuatorEnabled: true,
            operatingMode: 0,
        },
    },
);
await aggregator.add(endpoint);
```

When the bridge starts up, i get the following exception

`DatatypeError: Validating 1742525183699.aggregator.lock.doorLock.state.supportedOperatingModes.alwaysSet: Value "2047" is not in range of bit field (141)`

Thanks!

Complete stack trace:

```log
2025-03-28 16:04:00.545 INFO   ServerNodeStore      Opened 1742525183699 storage at /Users/daniel/.matter/1742525183699
2025-03-28 16:04:00.549 WARN   BasicInfor~ionServer Using development values for some BasicInformation attributes: hardwareVersion: 0 softwareVersion: 0
2025-03-28 16:04:00.573 INFO   BaseEventStore       Loaded volatile event store with next number 1001
2025-03-28 16:04:00.590 INFO   Endpoint             1742525183699 ready endpoint#: 0 type: RootNode (0x16) behaviors: 💤parts ✓index ✓basicInformation ✓accessControl ✓groupKeyManagement ✓generalCommissioning ✓administratorCommissioning ✓operationalCredentials ✓generalDiagnostics ✓commissioning ✓network 💤productDescription 💤subscription 💤sessions ✓events 💤controller ✓descriptor
2025-03-28 16:04:00.592 INFO   Endpoint             1742525183699.aggregator ready endpoint#: 1 type: Aggregator (0xe) behaviors: 💤parts ✓index ✓descriptor
2025-03-28 16:04:00.598 INFO   Endpoint             1742525183699.aggregator.onoff-1 ready endpoint#: 2 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓descriptor
2025-03-28 16:04:00.599 INFO   Transaction          Tx reactor<1742525183699.aggregator.descriptor.#updateDescriptor>#2f waiting on reactor<1742525183699.aggregator.descriptor.#updatePartsList>#2e
2025-03-28 16:04:00.599 INFO   Endpoint             1742525183699.aggregator.onoff-2 ready endpoint#: 3 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓descriptor
2025-03-28 16:04:00.603 ERROR  Transaction          Rolling back initialize<1742525183699.aggregator.lock>#3f due to error: Behaviors have errors
2025-03-28 16:04:00.604 FATAL  Logger               Unhandled error detected: Behaviors have errors
  at <anonymous> (/Users/daniel/Documents/workspace/matter.js/packages/node/src/endpoint/properties/Behaviors.ts:175:27)
  at all (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:705:25)
  at <anonymous> (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:695:17)
  Cause #0: Error initializing 1742525183699.aggregator.lock.doorLock
    at crash (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/internal/BehaviorBacking.ts:74:30)
    at ServerBehaviorBacking.[construct] (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/internal/BehaviorBacking.ts:90:13)
    at initializer (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:276:80)
    at invokeInitializer (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:573:30)
    at Construction.start (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:277:17)
    at Behaviors.#createBacking (/Users/daniel/Documents/workspace/matter.js/packages/node/src/endpoint/properties/Behaviors.ts:585:30)
    at Behaviors.activate (/Users/daniel/Documents/workspace/matter.js/packages/node/src/endpoint/properties/Behaviors.ts:337:18)
    at initializeBehaviors (/Users/daniel/Documents/workspace/matter.js/packages/node/src/endpoint/properties/Behaviors.ts:163:26)
    at actOffline (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/context/server/OfflineContext.ts:54:20)
    at Transaction.act (/Users/daniel/Documents/workspace/matter.js/packages/general/src/transaction/Tx.ts:95:29)
  Caused by: Validating 1742525183699.aggregator.lock.doorLock.state.supportedOperatingModes.alwaysSet: Value "2047" is not in range of bit field (141)
    at <anonymous> (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/state/validation/ValueValidator.ts:192:27)
    at Object.supportedOperatingModes (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/state/validation/conformance.ts:32:13)
    at validateStruct (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/state/validation/ValueValidator.ts:256:28)
    at Object.validate (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/state/managed/Datasource.ts:97:13)
    at finalizeState (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/internal/ServerBehaviorBacking.ts:59:29)
    at ServerBehaviorBacking.invokeInitializer (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/internal/ServerBehaviorBacking.ts:67:9)
    at ServerBehaviorBacking.[construct] (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/internal/BehaviorBacking.ts:85:34)
    at initializer (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:276:80)
    (see parent frames)
/Users/daniel/Documents/workspace/matter.js/packages/node/src/endpoint/properties/Behaviors.ts:175
                causes => new EndpointBehaviorsError(causes),
                          ^


EndpointBehaviorsError [AggregateError]: Behaviors have errors
    at <anonymous> (/Users/daniel/Documents/workspace/matter.js/packages/node/src/endpoint/properties/Behaviors.ts:175:27)
    at all (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:705:25)
    at <anonymous> (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:695:17) {
  [errors]: [
    BehaviorInitializationError: Error initializing 1742525183699.aggregator.lock.doorLock
        at crash (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/internal/BehaviorBacking.ts:74:30)
        at ServerBehaviorBacking.[construct] (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/internal/BehaviorBacking.ts:90:13)
        at initializer (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:276:80)
        at invokeInitializer (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:573:30)
        at Construction.start (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:277:17)
        at Behaviors.#createBacking (/Users/daniel/Documents/workspace/matter.js/packages/node/src/endpoint/properties/Behaviors.ts:585:30)
        at Behaviors.activate (/Users/daniel/Documents/workspace/matter.js/packages/node/src/endpoint/properties/Behaviors.ts:337:18)
        at initializeBehaviors (/Users/daniel/Documents/workspace/matter.js/packages/node/src/endpoint/properties/Behaviors.ts:163:26)
        at actOffline (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/context/server/OfflineContext.ts:54:20)
        at Transaction.act (/Users/daniel/Documents/workspace/matter.js/packages/general/src/transaction/Tx.ts:95:29) {
      cause: DatatypeError: Validating 1742525183699.aggregator.lock.doorLock.state.supportedOperatingModes.alwaysSet: Value "2047" is not in range of bit field (141)
          at <anonymous> (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/state/validation/ValueValidator.ts:192:27)
          at Object.supportedOperatingModes (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/state/validation/conformance.ts:32:13)
          at validateStruct (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/state/validation/ValueValidator.ts:256:28)
          at Object.validate (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/state/managed/Datasource.ts:97:13)
          at finalizeState (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/internal/ServerBehaviorBacking.ts:59:29)
          at ServerBehaviorBacking.invokeInitializer (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/internal/ServerBehaviorBacking.ts:67:9)
          at ServerBehaviorBacking.[construct] (/Users/daniel/Documents/workspace/matter.js/packages/node/src/behavior/internal/BehaviorBacking.ts:85:34)
          at initializer (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:276:80)
          at invokeInitializer (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:573:30)
          at Construction.start (/Users/daniel/Documents/workspace/matter.js/packages/general/src/util/Construction.ts:277:17) {
        code: 141,
        clusterCode: undefined
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by Apollon77**
* Fix Value validation for bitfield-ranges (fixes #1834)
* Add check in DoorLock that "alwaysSet bits" are also set
* regen model with 1.4 references
* Fix DoorLock range definition for alwaysSet

### CODE REVIEW

File: packages/node/src/behaviors/door-lock/DoorLockServer.ts [hunk 1]
```diff
@@ -5,13 +5,22 @@
...
+import { ImplementationError } from "#general";
 import { DoorLockBehavior } from "./DoorLockBehavior.js";
 import LockState = DoorLock.LockState;
 
 /**
  * This is the default server implementation of {@link DoorLockBehavior}.
  */
 export class DoorLockServer extends DoorLockBehavior {
+    override initialize() {
+        if (!this.state.supportedOperatingModes.alwaysSet) {
```
Comment (lauckhart) [inline packages/node/src/behaviors/door-lock/DoorLockServer.ts:17]: This doesn't test all of the bits (=== 2047 might be better?) and only catches values at init time. Nbd I suppose given that this is something of a hack anyway

**Review by lauckhart — APPROVED** [review]

File: packages/node/src/behaviors/door-lock/DoorLockServer.ts (hunk 1 above)
Comment (Apollon77) [reply packages/node/src/behaviors/door-lock/DoorLockServer.ts]: adjusted,.,and yes if someone wants to hack it that he always can ... we can just try to support :-)
