### PR TITLE
Fix message size check

### LINKED ISSUE #573: Ignoring UDP message with size
Hi,
first of all thank you for your great work with matter.js.
I updated my package (matterbridge) to 
    "@project-chip/matter-node.js": "^0.7.2",
    "@project-chip/matter.js": "^0.7.2",
and since then I receive continuously these warning messages:
```
2023-12-12 16:59:19.321 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:19.322 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:19.323 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from fe80::1c3b:c686:eba1:d3b1%eth0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:19.323 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from fe80::1c3b:c686:eba1:d3b1%eth0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:19.379 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:19.379 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:19.381 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from fe80::1c3b:c686:eba1:d3b1%wlan0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:19.382 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from fe80::1c3b:c686:eba1:d3b1%wlan0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:22.334 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:22.334 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:22.335 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from fe80::1c3b:c686:eba1:d3b1%eth0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:22.336 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from fe80::1c3b:c686:eba1:d3b1%eth0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:22.348 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:22.349 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:22.351 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from fe80::1c3b:c686:eba1:d3b1%wlan0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:22.351 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from fe80::1c3b:c686:eba1:d3b1%wlan0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:31.348 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:31.349 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:31.350 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from fe80::1c3b:c686:eba1:d3b1%eth0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:31.350 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from fe80::1c3b:c686:eba1:d3b1%eth0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:31.361 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:31.362 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:31.363 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from fe80::1c3b:c686:eba1:d3b1%wlan0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 16:59:31.364 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from fe80::1c3b:c686:eba1:d3b1%wlan0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:34.103 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:34.105 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:34.107 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from fe80::1c3b:c686:eba1:d3b1%eth0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:34.108 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from fe80::1c3b:c686:eba1:d3b1%eth0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:34.131 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:34.133 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:34.134 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from fe80::1c3b:c686:eba1:d3b1%wlan0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:34.136 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from fe80::1c3b:c686:eba1:d3b1%wlan0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:37.109 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:37.111 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:37.112 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from fe80::1c3b:c686:eba1:d3b1%eth0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:37.113 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from fe80::1c3b:c686:eba1:d3b1%eth0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:37.203 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:37.204 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:37.206 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from fe80::1c3b:c686:eba1:d3b1%wlan0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:00:37.207 WARN  UdpChannelNode       Ignoring UDP message with size 1314 from fe80::1c3b:c686:eba1:d3b1%wlan0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:01:04.717 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:01:04.718 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:01:04.719 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from fe80::1c3b:c686:eba1:d3b1%eth0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:01:04.719 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from fe80::1c3b:c686:eba1:d3b1%eth0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:01:04.749 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:01:04.750 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from 192.168.1.181:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:01:04.752 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from fe80::1c3b:c686:eba1:d3b1%wlan0:5353, which is larger than the maximum allowed size of 1280.
2023-12-12 17:01:04.752 WARN  UdpChannelNode       Ignoring UDP message with size 1407 from fe80::1c3b:c686:eba1:d3b1%wlan0:5353, which is larger than the maximum allowed size of 1280.
```
I saw in the changelog this:
- Handles too huge UDP messages correctly by dropping such messages.
Is it correct to have all these messages dropped?
My best.

### PR DESCRIPTION
**Pull request by Apollon77**
The message size check was added in the wrong place and so also affecting MDNS (where formally such messages are also too long but accepted potentially). For sending the specification states:
```
Messages sent over TCP or BTP over BLE transports MAY exceed the message size limit if both nodes are capable of supporting larger message sizes.
```
so I just added logging for now. Should not happen that we generate too big messages.

fixes #573

### CODE REVIEW

**Comment by Apollon77** [comment]
according to discord this fixes commissioning issues with eve device

File: packages/matter.js/src/protocol/ExchangeManager.ts [hunk 1]
```diff
@@ -69,8 +77,16 @@ export class ExchangeManager<ContextT> {
...
 
     addTransportInterface(netInterface: TransportInterface) {
+        const udpInterface = netInterface instanceof UdpInterface;
         this.transportListeners.push(
             netInterface.onData((socket, data) => {
+                if (udpInterface && data.length > MAX_MESSAGE_SIZE) {
+                    logger.warn(
+                        `Ignoring UDP message with size ${data.length} from ${socket.name}, which is larger than the maximum allowed size of ${MAX_MESSAGE_SIZE}.`,
+                    );
+                    return;
```
Comment (lauckhart) [inline packages/matter.js/src/protocol/ExchangeManager.ts:87]: Do you think maybe this should be a warning too? Regardless of what the spec says, if someone sends the packet and we receive it sends like processing it is most likely what the user would want.

**Review by lauckhart — APPROVED** [review]

File: packages/matter.js/src/protocol/ExchangeManager.ts (hunk 1 above)
Comment (Apollon77) [reply packages/matter.js/src/protocol/ExchangeManager.ts:87]: Thats a good question :-)

On the other hand specs say:
> A message received over UDP that exceeds this message size limit SHALL NOT be processed.

I would respect hat for now until it first time happened and breaks for someone
