### PR TITLE
Handful of small improvements & fixes

### LINKED ISSUE #1086: Scraper generates wrong Names when deprecated names are included
See DoorLock cluster.

When the table contains a new and a deprecated name of an attribute with an empty line between them then this is all concatinated, leading to strange names.
This mainly affects Doorlock but in approx 20 cases.

I would favor a scraper/generator fix rather then overrides.

### PR DESCRIPTION
**Pull request by lauckhart**
- Add parent device types to DeviceTypeList for derived clusters
- Fix imported garbage in some DoorLock field names
- Change typing for Behavior#features to include disabled features
- Explicitly define DescriptorServer as an endpoint requirement so attributes are configurable in TS
- Add DescriptorServer#addTag to make adding tags more convenient
- Modify DescriptorServer#addDeviceType to accept device type name to simplify avoidance of cyclical dependencies
- Modify additional behaviors to add device types when DT is implied by behavior's presence

fixes #1086

### CODE REVIEW

File: packages/matter.js/src/behavior/definitions/descriptor/DescriptorServer.ts [hunk 1]
```diff
@@ -48,23 +52,76 @@ export class DescriptorServer extends DescriptorBehavior {
                     revision: partType.deviceRevision,
                 },
             ];
+            for (
```
Comment (Apollon77) [inline packages/matter.js/src/behavior/definitions/descriptor/DescriptorServer.ts:55]: See discussion in Discord ... it is unclear which consequences this has based on specs and "duplicate condition" for device types.
So I would propose to comment it out ( so that it is easy to readd based on the clarification on spec level ... for now lets just allow a dev to add it manually

File: packages/matter.js/src/behavior/definitions/descriptor/DescriptorServer.ts [hunk 2]
```diff
@@ -48,23 +52,76 @@ export class DescriptorServer extends DescriptorBehavior {
...
                 }
             }
             list.push(newDeviceType);
         }
-        this.state.deviceTypeList = list;
+    }
+
+    /**
+     * Add semantic tags.  This is a shortcut for deduped insert into the tagList cluster attribute.
+     */
```
Comment (Apollon77) [inline packages/matter.js/src/behavior/definitions/descriptor/DescriptorServer.ts:100]: Please add here the info that for this method to work the feature needs to be enabled, so that devs see it at least in the IDE if they look

File: packages/matter.js/src/behavior/definitions/device-energy-management/DeviceEnergyManagementServer.ts [hunk 3]
```diff
@@ -15,4 +14,10 @@ import { DeviceEnergyManagementBehavior } from "./DeviceEnergyManagementBehavior
  * default. You should use {@link DeviceEnergyManagementServer.with} to specialize the class for the features your
  * implementation supports.
  */
-export class DeviceEnergyManagementServer extends DeviceEnergyManagementBehavior {}
+export class DeviceEnergyManagementServer extends DeviceEnergyManagementBehavior {
+    override initialize() {
+        // Technically ElectricalSensor also requires Device EnergyManagementMode (as of Matter 1.3) but no other device
+        // type requires DeviceEnergyManagement
+        this.agent.get(DescriptorServer).addDeviceTypes("ElectricalSensor");
```
Comment (Apollon77) [inline packages/matter.js/src/behavior/definitions/device-energy-management/DeviceEnergyManagementServer.ts:21]: Formally check that a PowerTopology cluster also exists on the endpoint because that one is the mandatory one?

File: packages/matter.js/src/behavior/definitions/power-topology/PowerTopologyServer.ts [hunk 4]
```diff
@@ -26,6 +27,8 @@ const PowerTopologyBase = PowerTopologyBehavior.with(
  */
 export class PowerTopologyServerLogic extends PowerTopologyBase {
     override initialize(): void {
+        this.agent.get(DescriptorServer).addDeviceTypes("ElectricalSensor");
```
Comment (Apollon77) [inline packages/matter.js/src/behavior/definitions/power-topology/PowerTopologyServer.ts:30]: Formally check that a either Electrical Power Measurement or Electrical Energy Measurement cluster also exists on the endpoint because it is only allowed in this combination?

File: models/src/v1.3/spec.ts [hunk 5]
```diff
@@ -11650,9 +11650,22 @@ export const SpecMatter = Matter({
                         "\n" +
                         "† The PIN/RFID Code is an obsolete field name, use PINCode instead.",
                     xref: { document: "cluster", section: "5.2.10.1" },
-                    children: [
-                        Field({ name: "PinCodePinRfidCode", id: 0x0, type: "octstr", conformance: "[COTA & PIN]" })
-                    ]
+
+                    children: [Field({
+                        name: "PinCode", id: 0x0, type: "octstr", conformance: "[COTA & PIN]",
```
Comment (Apollon77) [inline models/src/v1.3/spec.ts:11655]: Thats great ... please also regenerate model :-) because seems thats missing

File: packages/matter.js/src/behavior/definitions/descriptor/DescriptorServer.ts (hunk 1 above)
Comment (lauckhart) [reply packages/matter.js/src/behavior/definitions/descriptor/DescriptorServer.ts:55]: OK

File: packages/matter.js/src/behavior/definitions/descriptor/DescriptorServer.ts (hunk 2 above)
Comment (lauckhart) [reply packages/matter.js/src/behavior/definitions/descriptor/DescriptorServer.ts:100]: OK

File: packages/matter.js/src/behavior/definitions/device-energy-management/DeviceEnergyManagementServer.ts (hunk 3 above)
Comment (lauckhart) [reply packages/matter.js/src/behavior/definitions/device-energy-management/DeviceEnergyManagementServer.ts:21]: Meant to revert this file

File: packages/matter.js/src/behavior/definitions/power-topology/PowerTopologyServer.ts (hunk 4 above)
Comment (lauckhart) [reply packages/matter.js/src/behavior/definitions/power-topology/PowerTopologyServer.ts:30]: Yes, good idea

**Review by Apollon77 — APPROVED** [review]
Awesome, thank you!
