### PR TITLE
Ignore Regulatory config updates with "general purpose" values

### LINKED ISSUE #220: Failing to pair with Google Home on Android - 7/18 baseline
Pairing with Google Home on Android fails 

Using a fresh clone on 7/18 followed by:

cd matter.js
npm i
npm run  matter-device

UI reports "Something went wrong"

Log attached. Separately, paring succeeded with IOS, Amazon and SmartThings.

[mater.txt](https://github.com/project-chip/matter.js/files/12089001/mater.txt)

### PR DESCRIPTION
**Pull request by Apollon77**
fixes #220

@JimBuzbee if you like try it out

### CODE REVIEW

**Comment by JimBuzbee** [comment]
Fixes issue for me.

File: packages/matter.js/src/cluster/server/GeneralCommissioningServer.ts [hunk 1]
```diff
@@ -54,29 +54,32 @@ export const GeneralCommissioningClusterHandler: (options?: {
...
+            let validValues;
+            switch (locationCapabilityValue) {
+                case (RegulatoryLocationType.Outdoor):
+                    validValues = [RegulatoryLocationType.Outdoor];
+                    break;
+                case (RegulatoryLocationType.Indoor):
+                    validValues = [RegulatoryLocationType.Indoor];
+                    break;
+                case (RegulatoryLocationType.IndoorOutdoor):
+                    validValues = [RegulatoryLocationType.Indoor, RegulatoryLocationType.Outdoor];
```
Comment (lauckhart) [inline packages/matter.js/src/cluster/server/GeneralCommissioningServer.ts:73]: I can't find mention in the specification where it says Indoor/Outdoor is illegal for RegulatoryConfig. In fact my reading is the default would be Indoor/Outdoor if LocationCapability is Indoor/Outdoor. Maybe we should accept the value?

Comment (Apollon77) [reply packages/matter.js/src/cluster/server/GeneralCommissioningServer.ts:73]: I checkChip tool again and yes it is accepted (in fact makes no sense, but) :-) I adjust

**Review by lauckhart — APPROVED** [review]
